services:
  shard1:
    image: postgres:15
    container_name: shard1_db
    environment:
      POSTGRES_DB: bookstore_shard1
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: securepassword123
    ports:
      - "5431:5432"
    volumes:
      - ./shard1:/var/lib/postgresql/data
      - ./sql-scripts:/docker-entrypoint-initdb.d
      - ./shard1/postgresql.conf:/etc/postgresql/postgresql.conf
    networks:
      - shard_network

  shard2:
    image: postgres:15
    container_name: shard2_db
    environment:
      POSTGRES_DB: bookstore_shard2
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: securepassword123
    ports:
      - "5432:5432"
    volumes:
      - ./shard2:/var/lib/postgresql/data
      - ./sql-scripts:/docker-entrypoint-initdb.d
      - ./shard2/postgresql.conf:/etc/postgresql/postgresql.conf
    networks:
      - shard_network

  shard3:
    image: postgres:15
    container_name: shard3_db
    environment:
      POSTGRES_DB: bookstore_shard3
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: securepassword123
    ports:
      - "5433:5432"
    volumes:
      - ./shard3:/var/lib/postgresql/data
      - ./sql-scripts:/docker-entrypoint-initdb.d
      - ./shard3/postgresql.conf:/etc/postgresql/postgresql.conf
    networks:
      - shard_network

networks:
  shard_network:
    driver: bridge
